version: '2'
services:
  consul:
    image: consul:1.4.4
    command:
      - agent
      - -server
      - -bootstrap-expect=1
      - -node=node1
      - -bind=0.0.0.0
      - -client=0.0.0.0
      - -datacenter=dc1
      - -ui
    ports:
      - 8500:8500
  registrator:
    command: -internal consul://consul:8500
    privileged: true
    image: gliderlabs/registrator:latest
    restart: always
    links:
      - consul
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock